version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/express-app

permissions:
  - object: /home/ubuntu
    owner: ubuntu
    group: ubuntu
    type:
      - directory
      - file

hook:
  ApplicationStop:
    - location: scripts/application_stop.sh
      runas: ubuntu
  BeforeIntall:
    - location: scripts/before_install.sh
      runas: ubuntu
  ApplicationStart:
    - location: sciprts/application_start.sh
      runas: ubuntu