version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/express-app

hook:
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 300
      runas: root
  BeforeIntall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: sciprts/application_start.sh
      timeout: 300
      runas: root