version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/express-app

hook:
  ApplicationStop:
    - location: /home/ubuntu/express-app/scripts/application_stop.sh
      timeout: 300
      runas: ubuntu
  BeforeIntall:
    - location: /home/ubuntu/express-app/scripts/before_install.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: /home/ubuntu/express-app/sciprts/application_start.sh
      timeout: 300
      runas: ubuntu